### ISSUE TITLE
Error: [DropboxUploader] #268698113 Login unsuccessful.

### ISSUE THREAD

**Issue by stccorp** [jakajancar/DropboxUploader#45]
I was using version 1.12 and started getting the error.  I am now using the  latest 1.19 version and still get the error.  I am using example.php.   With the same username and password I can log in directly on dropbox website

**Comment by hakre** [comment]
@onurgozupek Can you please verify the version you're using and post it here?

**Comment by onurgozupek** [comment]
Version is 1.1.19 and the error code is : Error: [DropboxUploader] #268698113 Login unsuccessful.

**Comment by prasanth88** [comment]
I have integrate dropbox in my website and it was working till this day(15-1-2015) up to 5.30 AM. But now its showing as error when we tried to upload the file. Error is "Error: [DropboxUploader] #268698113 Login unsuccessful.". What should i do?

**Comment by prasanth88** [comment]
Please do reply..Anyone got the solution??

**Comment by stccorp** [comment]
I found no solution.  I wrote to DropBox and they told me they dont support external libraries.


The problem with dropbox is that they are morons.  Instead of doing like Google, They implemented they keys as ints.  Google did it with chars.  That mean you need 64 bit OS to use DropBox, While you can use 32bit OS for Google.  Since I cannot change my OS, I replace DropBpx with Google Drive.  I dont suggest using anything other that DropBox API, since any change DropBox does will affect you

**Comment by eberswine** [comment]
This is a bug on my install as well.

I am sure the author is looking for a fix for this!

**Comment by alexeydevederkin** [comment]
Hey.

It seems that with correct login/password Dropbox doesn’t send ```"csrf_token"``` in the body of response.

So I wrote in ```private function login()``` this:
```php
if (stripos($data, '{"status": "OK"') === FALSE)
    throw new Exception('Login unsuccessful.', self::CODE_LOGIN_ERROR);
```
instead of this:
```php
if (stripos($data, '{"status": "OK", "csrf_token": "') === FALSE)
    throw new Exception('Login unsuccessful.', self::CODE_LOGIN_ERROR);
```
Now it works good.

**Comment by eberswine** [comment]
Great! I tested this on 2 installs and it works perfect. Thanks @alexeydevederkin

**Comment by onurgozupek** [comment]
Finally I have found the solution :) It's a mix from a couple of solutions.

First: Contants
```
    const DROPBOX_UPLOAD_LIMIT_IN_BYTES = 314572800;
    const HTTPS_DROPBOX_COM_HOME        = 'https://www.dropbox.com/home';
    const HTTPS_DROPBOX_COM_LOGIN       = 'https://www.dropbox.com/login';
    const HTTPS_DROPBOX_COM_LOGINACTION = 'https://www.dropbox.com/ajax_login';
    const HTTPS_DROPBOX_COM_UPLOAD      = 'https://dl-web.dropbox.com/upload';
    const HTTPS_DROPBOX_COM_LOGOUT      = 'https://www.dropbox.com/logout';
```

Second: private function login()
```
private function login() {
        $data  = $this->request(self::HTTPS_DROPBOX_COM_LOGIN);
        $token = $this->extractTokenFromLoginForm($data);

        $postData = array(
            'login_email'    => (string) $this->email,
            'login_password' => (string) $this->password,
            't'              => $token
        );
        $data     = $this->request(self::HTTPS_DROPBOX_COM_LOGINACTION, http_build_query($postData));
        if (stripos($data, '{"status": "OK"') === FALSE)
    		throw new Exception('Login unsuccessful.', self::CODE_LOGIN_ERROR);

        $this->loggedIn = TRUE;
    }
```

Third: Uploading code (example.php)
```
try {
	$uploader = new DropboxUploader('$DROPBOX_USERNAME', '$DROPBOX_PASSWORD');
	$uploader->upload($FILE_TO_UPLOAD, $DROPBOX_PATH);
} catch (Exception $e) {
	// Handle Upload Exceptions
	$label = ($e->getCode() && DropboxUploader::FLAG_DROPBOX_GENERIC) ? 'DropboxUploader' : 'Exception';
	$error = sprintf("[%s] #%d %s", $label, $e->getCode(), $e->getMessage());
	echo '<span style="color: red">Error: ' . htmlspecialchars($error) . '</span>';
}
```

Working DropboxUploader.php can be downloaded here: https://dl.dropboxusercontent.com/u/410774/DropboxUploader.php (PS: @jakajancar let me know after you check this file. I will delete it later)

Thanks to @alexeydevederkin, Destiny on Stackoveflow http://stackoverflow.com/questions/27640973/php-dropbox-uploader-class-name-fatal-error and of course @jakajancar

**Comment by PheRum** [comment]
Uncaught exception 'Exception' with message 'Login unsuccessful

**Comment by stccorp** [comment]
It worked for me.  Thank you

**Comment by fabuio** [comment]
Fix ok for me. Thank you Jongotlin

**Comment by alessandrobarbetti** [comment]
Worked for me too.

**Comment by hakre** [comment]
@onurgozupek can you please check if with latest 1.1.21 you don't have the login error any longer?

**Comment by onurgozupek** [comment]
@hakre Yes it worked! Uploaded without error... Thank you very much...

**Comment by hakre** [comment]
@onurgozupek  You're welcome. Thanks for testing and taking care.

**Comment by sakirkaida** [comment]
i am getting this Error: [DropboxUploader] #268698113 Login unsuccessful. @V 1.1.22
please help me how to solve this

**Comment by bidid** [comment]
i also am getting this Error: [DropboxUploader] #268698113 Login unsuccessful. @V 1.1.22
please help me how to solve this

**Comment by madept** [comment]
i also am getting this Error: [DropboxUploader] #268698113 Login unsuccessful. @v 1.1.22
please help me how to solve this
