### ISSUE TITLE
Remove version number in files

### ISSUE THREAD

**Issue by jongotlin** [jakajancar/DropboxUploader#48]
I think the version number should be removed from `composer.json` and `DropboxUploader.php`. Lets just have the version bump when you make a new tag for packagist.

**Comment by hakre** [comment]
Hi @jongotlin, for which reason?

**Comment by jongotlin** [comment]
Yes. And to follow the standard to have the version number in a git tag commit. Having both is just confusing.

**Comment by hakre** [comment]
For the `composer.json` I'm with you, for the source file I think it's useful to keep that in. In #50 I've removed it from composer.json.

And there is no need for PRs to bump the version, I normally do that on my own, the version bump commit is the change-log as well.

**Comment by hakre** [comment]
@jongotlin I close the issue, feel free to re-open at any time.
