### ISSUE TITLE
Exception: Cannot extract login CSRF token.

### ISSUE THREAD

**Issue by iwazaru** [jakajancar/DropboxUploader#52]
I think Dropbox may have changed the way they handle login. Since a few days, running phpunit tests returns this:

    ESSSS.

    Time: 1.81 seconds, Memory: 3.75Mb

    There was 1 error:

    1) DropboxIntegrationTest::testLogin
    Exception: Cannot extract login CSRF token.

    /Users/clement/Desktop/DropboxUploader/DropboxUploader.php:260
    /Users/clement/Desktop/DropboxUploader/DropboxUploader.php:179
    /Users/clement/Desktop/DropboxUploader/test/integration/DropboxIntegrationTest.php:39
    phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
    phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138

    FAILURES!
    Tests: 3, Assertions: 10, Errors: 1, Skipped: 4.

**Comment by josemalonsom** [comment]
Same here.

They seem to have returned to the old format for sending the token used before e19ce1c. Created a PR with the fix https://github.com/hakre/DropboxUploader/pull/3.

**Comment by dizda** [comment]
:+1:

**Comment by clemlatz** [comment]
:thumbsup:
